services:
  transaction-db:
    image: postgres:15-alpine
    container_name: transaction-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  transaction-service:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://transaction-db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      # Adding a secret key for your security logic
      - SECURITY_JWT_SECRET=${JWT_SECRET}
    depends_on:
      - transaction-db