spring.application.name=WalletService

# Server
server.port=${SERVER_PORT:8085}

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/wallet_service_db}
spring.datasource.username=${DB_USERNAME:wallet}
spring.datasource.password=${DB_PASSWORD:wallet123}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=${REDIS_TIMEOUT:2s}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:/}

# Security / JWT (for later auth wiring)
jwt.secret=${JWT_SECRET:QuoocsCuongwf_EFEWalletProject_AuthService_SecretKey_ChangeThisToAtLeast64BytesLong}
app.security.jwt.secret=${JWT_SECRET:QuoocsCuongwf_EFEWalletProject_AuthService_SecretKey_ChangeThisToAtLeast64BytesLong}
app.security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
redis.host=${REDIS_HOST:localhost}
redis.port=${REDIS_PORT:6379}

# Port cho gRPC Server
spring.grpc.server.port=9090
